name: 'Update PKGBUILD'
description:
  'Updates a PKGBUILD sources and checksums when a new version is available'
author: 'Rodrigo Tavares <me@rodrigotavar.es>'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  config-file:
    description: The path to the configuration file JSON
    required: true
  packages-path:
    description: The path to the packages directory
    required: true

runs:
  using: node20
  main: dist/index.js
