name: Update Packages

on:
  workflow_dispatch:
  schedule:
    - cron: '25 4 * * *'

permissions:
  contents: write
  actions: write

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: config
      uses: ./actions
      with:
        config-file: packages-config.json
        packages-path: packages
    - name: Trigger Sync Workflow
      if: steps.config.outputs.changes == 'true'
      run: gh workflow run sync-repo.yml --ref main
      env:
        GH_TOKEN: ${{ github.token }}