name: Add/Remove Packages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'config.json'
      - '.github/workflows/setup.yml'
      - '.github/workflows/rebuild.yml'

permissions:
  packages: write
  contents: write

concurrency:
  group: "release"

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      enc-gpg: ${{ steps.config.outputs.enc-gpg }}
      repo-name: ${{ steps.config.outputs.repo-name }}
      packager: ${{ steps.config.outputs.packager }}

      deleted: ${{ steps.deleted-files.outputs.deleted_files }}
      added: ${{ steps.added-files.outputs.added_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - id: config
        uses: ./.github/actions/load-config
      - name: Get deleted files
        id: deleted-files
        uses: tj-actions/changed-files@v43
        with:
          path: packages
          diff_relative: true
          json: true
          escape_json: false
      - name: Print deleted files
        run: echo ${{ steps.deleted-files.outputs.deleted_files }}
      - name: Get added files
        id: added-files
        uses: tj-actions/changed-files@v43
        with:
          path: packages
          diff_relative: true
          dir_names: true
          dir_names_max_depth: 1
          json: true
          escape_json: false
      - name: Print added files
        run: echo ${{ steps.added-files.outputs.added_files }}


  added:
    runs-on: ubuntu-latest
    needs: variables
    
    if: ${{ needs.variables.outputs.added != '[]' }}

    strategy:
      matrix:
        package: ${{ fromJson(needs.variables.outputs.added) }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build ${{ matrix.package }}
      uses: ./.github/actions/archlinux
      env:
        PACKAGER: ${{ needs.variables.outputs.packager }}
        SECRET: ${{ secrets.ENCRYPTION_KEY }}
        GPGKEY: ${{ needs.variables.outputs.enc-gpg }}
      with:
        dir: packages/${{ matrix.package }}
        run: makepkg -sr --sign -C -c --noconfirm --noprogressbar
    - name: Upload new package ${{ matrix.package }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: repository
        file: packages/${{ matrix.package }}/*.pkg.*
        file_glob: true
        overwrite: false

  deleted:
    runs-on: ubuntu-latest
    needs: variables

    if: ${{ needs.variables.outputs.deleted != '[]' }}

    strategy:
      matrix:
        package: ${{ fromJson(needs.variables.outputs.deleted) }}
    
    steps:
    - name: Delete old package ${{ matrix.package }}
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: repository
        assets: packages/${{ matrix.package }}*
