name: Rebuild Archlinux Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/rebuild.yml'
  workflow_run:
    workflows:
      - Setup
      - Update Signing Key
    types:
      - completed
  release:
    types:
      - deleted
permissions:
  packages: write
  contents: write

concurrency:
  group: "release"

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      enc-gpg: ${{ steps.config.outputs.enc-gpg }}
      repo-name: ${{ steps.config.outputs.repo-name }}
      packager: ${{ steps.config.outputs.packager }}

      packages: ${{ steps.set-packages.outputs.packages }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: main
    - id: config
      uses: ./.github/actions/load-config
    - id: set-packages
      uses: ./.github/actions/list-packages

  remove-release:
    runs-on: ubuntu-latest
    needs:
      - variables
    steps:
      - name: Delete release
        run: gh release delete repository -y --cleanup-tag --repo ${{ github.repository }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-package:
    runs-on: ubuntu-latest
    needs: 
      - variables
      - remove-release

    strategy:
      matrix:
        package: ${{ fromJson(needs.variables.outputs.packages) }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: main
    - name: Build ${{ matrix.package }}
      uses: ./.github/actions/archlinux
      env:
        PACKAGER: ${{ needs.variables.outputs.packager }}
        SECRET: ${{ secrets.ENCRYPTION_KEY }}
        GPGKEY: ${{ needs.variables.outputs.enc-gpg }}
      with:
        dir: packages/${{ matrix.package }}
        run: makepkg -sr --sign -C -c --noconfirm --noprogressbar
    - name: Upload new package ${{ matrix.package }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: repository
        file: packages/${{ matrix.package }}/*.pkg.*
        file_glob: true
        overwrite: false
